/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author fernando
 */
public class MenuPrincipal extends javax.swing.JFrame {
    Principal viewPrincipal;
    Seguimiento viewSeguimiento;
    RGSTExpediente viewExpediente;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        viewPrincipal = new Principal();
        viewSeguimiento = new Seguimiento();
        viewExpediente = new RGSTExpediente();
        
        ShowJPanel(viewPrincipal);
        setResizable(false); //Evitar el redimensionamiento.
        setLocationRelativeTo(null);
        setTitle("Menu"); //Titulo.
        setSize(new Dimension(610, 375)); //Tamaño del JFrame
    }

    private void ShowJPanel(JPanel p) {
        /* Muestra el contenido del Jpanel p para que se muestre en content. */
        p.setSize(430, 280);
        p.setLocation(0, 0);

        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bttnExpediente = new javax.swing.JButton();
        bttnSeguimiento = new javax.swing.JButton();
        bttnConsultar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        bttnPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setForeground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttnExpediente.setBackground(new java.awt.Color(255, 153, 0));
        bttnExpediente.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        bttnExpediente.setForeground(new java.awt.Color(255, 255, 255));
        bttnExpediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Copia de historial1.png"))); // NOI18N
        bttnExpediente.setText("Expediente");
        bttnExpediente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(255, 153, 0)));
        bttnExpediente.setBorderPainted(false);
        bttnExpediente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnExpediente.setIconTextGap(15);
        bttnExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnExpedienteActionPerformed(evt);
            }
        });
        jPanel2.add(bttnExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 40));

        bttnSeguimiento.setBackground(new java.awt.Color(255, 153, 0));
        bttnSeguimiento.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        bttnSeguimiento.setForeground(new java.awt.Color(255, 255, 255));
        bttnSeguimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Copia de anadir.png"))); // NOI18N
        bttnSeguimiento.setText("Seguimiento");
        bttnSeguimiento.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(255, 153, 0)));
        bttnSeguimiento.setBorderPainted(false);
        bttnSeguimiento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnSeguimiento.setIconTextGap(15);
        bttnSeguimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSeguimientoActionPerformed(evt);
            }
        });
        jPanel2.add(bttnSeguimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 160, 40));

        bttnConsultar.setBackground(new java.awt.Color(255, 153, 0));
        bttnConsultar.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        bttnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        bttnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Copia de activo.png"))); // NOI18N
        bttnConsultar.setText("Consultar");
        bttnConsultar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(255, 153, 0)));
        bttnConsultar.setBorderPainted(false);
        bttnConsultar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnConsultar.setIconTextGap(15);
        jPanel2.add(bttnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 160, 40));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("© Grupo 2");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo (1) (1).png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 159, 350));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 22)); // NOI18N
        jLabel1.setText("Sistema de Trámite");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 266, -1));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 430, 280));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 410, -1));

        bttnPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hogar (1).png"))); // NOI18N
        bttnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnPrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(bttnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnExpedienteActionPerformed
        // TODO add your handling code here:
        ShowJPanel(viewExpediente);
    }//GEN-LAST:event_bttnExpedienteActionPerformed

    private void bttnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnPrincipalActionPerformed
        // TODO add your handling code here:
        ShowJPanel(viewPrincipal);
    }//GEN-LAST:event_bttnPrincipalActionPerformed

    private void bttnSeguimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSeguimientoActionPerformed
        // TODO add your handling code here:
        ShowJPanel(viewSeguimiento);
    }//GEN-LAST:event_bttnSeguimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnConsultar;
    private javax.swing.JButton bttnExpediente;
    private javax.swing.JButton bttnPrincipal;
    private javax.swing.JButton bttnSeguimiento;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
